//! SSH key management and connecting into VMs.
//!
//! Each profile owns one ed25519 keypair generated by the host `ssh-keygen`. The
//! public half is baked into the image as the `dev` user's `authorized_keys`; the
//! private half never leaves the host data directory. Secrets required inside an
//! SSH session are forwarded with `SendEnv` (the guest sshd `AcceptEnv`s them), so
//! they reach the session environment without ever landing on the guest disk.

use std::path::PathBuf;
use std::process::{Command, ExitStatus, Stdio};

use crate::error::{Error, Result};
use crate::paths::Layout;
use crate::secrets::SecretEnv;

/// Ensure the profile's SSH keypair exists, generating it if absent.
pub fn ensure_keypair(layout: &Layout, profile: &str) -> Result<()> {
    let key = layout.ssh_key(profile);
    let pubkey = layout.ssh_pubkey(profile);
    if key.exists() && pubkey.exists() {
        return Ok(());
    }
    which::which("ssh-keygen").map_err(|_| Error::ToolNotFound {
        tool: "ssh-keygen".to_owned(),
    })?;
    if let Some(parent) = key.parent() {
        std::fs::create_dir_all(parent)?;
    }

    // Recover just the public key if the private key is already present.
    if key.exists() && !pubkey.exists() {
        let out = Command::new("ssh-keygen")
            .args(["-y", "-f", &key.display().to_string()])
            .output()
            .map_err(|source| Error::CommandSpawn {
                cmd: "ssh-keygen -y".to_owned(),
                source,
            })?;
        if !out.status.success() {
            return Err(Error::CommandFailed {
                cmd: "ssh-keygen -y".to_owned(),
                code: out.status.code().unwrap_or(-1),
            });
        }
        std::fs::write(&pubkey, out.stdout)?;
        return Ok(());
    }

    let status = Command::new("ssh-keygen")
        .args([
            "-t",
            "ed25519",
            "-N",
            "",
            "-C",
            &format!("airlock-{profile}"),
            "-f",
            &key.display().to_string(),
        ])
        .output()
        .map_err(|source| Error::CommandSpawn {
            cmd: "ssh-keygen".to_owned(),
            source,
        })?;
    if !status.status.success() {
        return Err(Error::CommandFailed {
            cmd: "ssh-keygen".to_owned(),
            code: status.status.code().unwrap_or(-1),
        });
    }
    Ok(())
}

/// Everything needed to reach one VM's sshd over loopback.
#[derive(Clone, Debug)]
pub struct SshTarget {
    /// Host to connect to (always loopback today).
    pub host: String,
    /// Forwarded host port mapped to the guest's `:22`.
    pub port: u16,
    /// Guest username.
    pub user: String,
    /// Private key path.
    pub key: PathBuf,
    /// Per-profile `known_hosts` file.
    pub known_hosts: PathBuf,
}

impl SshTarget {
    /// Build a loopback target for a profile member.
    pub fn loopback(layout: &Layout, profile: &str, user: &str, port: u16) -> Self {
        Self {
            host: "127.0.0.1".to_owned(),
            port,
            user: user.to_owned(),
            key: layout.ssh_key(profile),
            known_hosts: layout.profile_data(profile).join("known_hosts"),
        }
    }
}

/// Build argv for the host `ssh` client (pure; unit-tested). `send_env` lists the
/// env var *names* to forward — values are supplied via the process environment,
/// never argv.
pub fn build_ssh_args(target: &SshTarget, send_env: &[String], command: &[String]) -> Vec<String> {
    let mut a = vec![
        "-i".to_owned(),
        target.key.display().to_string(),
        "-p".to_owned(),
        target.port.to_string(),
        "-o".to_owned(),
        "IdentitiesOnly=yes".to_owned(),
        "-o".to_owned(),
        "StrictHostKeyChecking=accept-new".to_owned(),
        "-o".to_owned(),
        format!("UserKnownHostsFile={}", target.known_hosts.display()),
        "-o".to_owned(),
        "LogLevel=ERROR".to_owned(),
    ];
    for name in send_env {
        a.push("-o".to_owned());
        a.push(format!("SendEnv={name}"));
    }
    a.push(format!("{}@{}", target.user, target.host));
    a.extend(command.iter().cloned());
    a
}

/// SSH into a VM, forwarding `secret_env` + `plain_env` into the session via
/// `SendEnv`. An empty `command` opens an interactive login shell.
pub fn connect(
    target: &SshTarget,
    secret_env: &[SecretEnv],
    plain_env: &[(String, String)],
    command: &[String],
) -> Result<ExitStatus> {
    which::which("ssh").map_err(|_| Error::ToolNotFound {
        tool: "ssh".to_owned(),
    })?;
    if let Some(parent) = target.known_hosts.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let mut send_names: Vec<String> = secret_env.iter().map(|s| s.guest_name.clone()).collect();
    send_names.extend(plain_env.iter().map(|(k, _)| k.clone()));

    let args = build_ssh_args(target, &send_names, command);
    let mut cmd = Command::new("ssh");
    cmd.args(&args);
    for s in secret_env {
        cmd.env(&s.guest_name, s.value.expose());
    }
    for (k, v) in plain_env {
        cmd.env(k, v);
    }
    cmd.stdin(Stdio::inherit())
        .stdout(Stdio::inherit())
        .stderr(Stdio::inherit());
    cmd.status().map_err(|source| Error::CommandSpawn {
        cmd: "ssh".to_owned(),
        source,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn build_ssh_args_forwards_names_not_values() {
        let target = SshTarget {
            host: "127.0.0.1".to_owned(),
            port: 2201,
            user: "dev".to_owned(),
            key: PathBuf::from("/data/web/id_ed25519"),
            known_hosts: PathBuf::from("/data/web/known_hosts"),
        };
        let send = vec!["GH_TOKEN".to_owned(), "ANTHROPIC_API_KEY".to_owned()];
        let args = build_ssh_args(&target, &send, &["claude".to_owned()]);

        assert!(args.contains(&"-p".to_owned()) && args.contains(&"2201".to_owned()));
        assert!(args.contains(&"SendEnv=GH_TOKEN".to_owned()));
        assert!(args.contains(&"dev@127.0.0.1".to_owned()));
        // Command comes last.
        assert_eq!(args.last().map(String::as_str), Some("claude"));
        // No secret values appear anywhere in argv.
        assert!(!args.iter().any(|a| a.contains("secret")));
    }

    #[test]
    fn ensure_keypair_generates_and_is_idempotent() -> anyhow::Result<()> {
        use std::path::PathBuf;

        if which::which("ssh-keygen").is_err() {
            return Ok(()); // environment without ssh-keygen; skip
        }
        let tmp = tempfile::tempdir()?;
        let layout = Layout::with_roots(tmp.path().join("data"), tmp.path().join("state"));
        layout.ensure_profile_dirs("web")?;

        ensure_keypair(&layout, "web")?;
        let key: PathBuf = layout.ssh_key("web");
        let pubkey: PathBuf = layout.ssh_pubkey("web");
        assert!(key.exists() && pubkey.exists());
        let pub_contents = std::fs::read_to_string(&pubkey)?;
        assert!(pub_contents.starts_with("ssh-ed25519"));

        // Idempotent: a second call must not change the key.
        let before = std::fs::read_to_string(&key)?;
        ensure_keypair(&layout, "web")?;
        assert_eq!(before, std::fs::read_to_string(&key)?);
        Ok(())
    }
}
